version: "3.3"
services:
    web:
        build: ./
        command: nodemon -L app.js
        ports:
            - "3081:3081"
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        depends_on:
            - mongo
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - ./data:/data/db